In [31]:
import numpy as np
import pandas as pd

## Aggregate functions

In [32]:
data = {
    'category':['A','B','B','A','B'],
    'stores':['s1','s1','s2','s2','s1'],
    'sales':[100,100,200,100,600],
    'quantity':[4,7,0,3,6],
    'date':['12-2024','13-2033','20-2030','10-2012','12-2020']
}
df = pd.DataFrame(data)
df

  category stores  sales  quantity     date
0        A     s1    100         4  12-2024
1        B     s1    100         7  13-2033
2        B     s2    200         0  20-2030
3        A     s2    100         3  10-2012
4        B     s1    600         6  12-2020

In [30]:
# we have aggreate functions sum, mean, median, min, max, count, std, var, prod

In [36]:
df['sales'].mean()

np.float64(220.0)

In [37]:
df['sales'].prod()

np.int64(120000000000)

In [38]:
df['sales'].count()

np.int64(5)

In [39]:
# etc

In [40]:
# We can also do it for multiple results

In [44]:
df['sales'].agg(['mean','median', 'min', 'max', 'count', 'std', 'var','sum']) # prod can change format of values so excluded that

mean        220.000000
median      100.000000
min         100.000000
max         600.000000
count         5.000000
std         216.794834
var       47000.000000
sum        1100.000000
Name: sales, dtype: float64

# Crostabs

In [46]:
pd.crosstab(df['stores'],df['category'])

category  A  B
stores
s1        1  2
s2        1  1

In [47]:
pd.crosstab(df['stores'],df['quantity'])

quantity  0  3  4  6  7
stores
s1        0  0  1  1  1
s2        1  1  0  0  0

In [48]:
pd.crosstab(df['stores'],df['sales'])

sales   100  200  600
stores
s1        2    0    1
s2        1    1    0